name: Parallel jobs
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo "first job"
  
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo "second job"

  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5 && echo "third job"