name: Secrets
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.PASS }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
